[
    [
        "powermenu",
        "5",
        "icon",
        "common/settings1.png"
    ],
    [
        "powermenu",
        "1037",
        "translatedPath",
        "ActivateWindow(Videos,Addons,return)"
    ],
    [
        "powermenu",
        "1037",
        "icon",
        "defaultaddonvideo.png"
    ],
    [
        "powermenu",
        "1038",
        "translatedPath",
        "ActivateWindow(MusicLibrary,Addons,return)"
    ],
    [
        "powermenu",
        "1038",
        "icon",
        "defaultaddonmusic.png"
    ],
    [
        "powermenu",
        "programs",
        "translatedPath",
        "ActivateWindow(Programs,Addons,return)"
    ],
    [
        "powermenu",
        "programs",
        "widgetTarget",
        "programs"
    ],
    [
        "powermenu",
        "programs",
        "icon",
        "defaultaddonprogram.png"
    ],
    [
        "powermenu",
        "31160",
        "icon",
        "common/exit1.png"
    ],
    [
        "powermenu",
        "13013",
        "translatedPath",
        "Reset"
    ],
    [
        "powermenu",
        "13013",
        "icon",
        "common/reboot1.png"
    ],
    [
        "powermenu",
        "13016",
        "translatedPath",
        "Powerdown"
    ],
    [
        "powermenu",
        "13016",
        "icon",
        "common/shutdown1.png"
    ],
    [
        "powermenu",
        "20126",
        "icon",
        "common/lock.png"
    ],
    [
        "10000.1",
        "latestmovies",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.pov/?name=32461&iconImage=dvd.png&mode=build_movie_list&action=tmdb_movies_latest_releases\",return)"
    ],
    [
        "10000.1",
        "latestmovies",
        "widgetTarget",
        "videos"
    ],
    [
        "10000.1",
        "latestmovies",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "10000.1",
        "latestmovies",
        "thumb",
        "image://special%3a%2f%2fhome%2faddons%2fplugin.video.pov%2fresources%2fskins%2fDefault%2fmedia%2fdvd.png/"
    ],
    [
        "10000.1",
        "recommendedmovies",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.pov/?mode=build_movie_list&action=trakt_recommendations&name=Movies&iconImage=special%3A%2F%2Fhome%2Faddons%2Fplugin.video.pov%2Fresources%2Fskins%2FDefault%2Fmedia%2Ftrakt.png\",return)"
    ],
    [
        "10000.1",
        "recommendedmovies",
        "widgetTarget",
        "videos"
    ],
    [
        "10000.1",
        "recommendedmovies",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "10000.1",
        "recommendedmovies",
        "thumb",
        "image://special%3a%2f%2fhome%2faddons%2fplugin.video.pov%2fresources%2fskins%2fDefault%2fmedia%2ftrakt.png/"
    ],
    [
        "10000.1",
        "truecrimedocumentaries",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.pov/?mode=build_trakt_list&user=lish408&slug=true-crime-documentary-series-film&list_id=11416887&list_type=user_lists&name=True+Crime+Documentary+Series+%26+Film\",return)"
    ],
    [
        "10000.1",
        "truecrimedocumentaries",
        "widgetTarget",
        "videos"
    ],
    [
        "10000.1",
        "truecrimedocumentaries",
        "widgetSortBy",
        "random"
    ],
    [
        "10000.1",
        "truecrimedocumentaries",
        "widgetSortBy.name",
        "Random"
    ],
    [
        "10000.1",
        "truecrimedocumentaries",
        "widgetSortByName",
        "Random"
    ],
    [
        "10000.1",
        "truecrimedocumentaries",
        "widgetSortOrder",
        "ascending"
    ],
    [
        "10000.1",
        "truecrimedocumentaries",
        "widgetSortOrder.name",
        "ascending"
    ],
    [
        "10000.1",
        "truecrimedocumentaries",
        "widgetSortOrderName",
        "ascending"
    ],
    [
        "10000.1",
        "truecrimedocumentaries",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "10000.1",
        "truecrimedocumentaries",
        "thumb",
        "image://special%3a%2f%2fhome%2faddons%2fplugin.video.pov%2fresources%2fskins%2fDefault%2fmedia%2ftrakt.png/"
    ],
    [
        "10000.1",
        "animeshows",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.pov/?name=Series+Trending&iconImage=tv.png&mode=build_tvshow_list&action=trakt_tvanime_trending\",return)"
    ],
    [
        "10000.1",
        "animeshows",
        "widgetTarget",
        "videos"
    ],
    [
        "10000.1",
        "animeshows",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "10000.1",
        "animeshows",
        "thumb",
        "image://special%3a%2f%2fhome%2faddons%2fplugin.video.pov%2fresources%2fskins%2fDefault%2fmedia%2ftv.png/"
    ],
    [
        "10000.1",
        "currentshows",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.pov/?name=32449&iconImage=trending.png&mode=build_tvshow_list&action=trakt_tv_trending_recent\",return)"
    ],
    [
        "10000.1",
        "currentshows",
        "widgetTarget",
        "videos"
    ],
    [
        "10000.1",
        "currentshows",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "10000.1",
        "currentshows",
        "thumb",
        "image://special%3a%2f%2fhome%2faddons%2fplugin.video.pov%2fresources%2fskins%2fDefault%2fmedia%2ftrending.png/"
    ],
    [
        "10000.1",
        "recommendedshows",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.pov/?mode=build_tvshow_list&action=trakt_recommendations&name=TV+Shows&iconImage=special%3A%2F%2Fhome%2Faddons%2Fplugin.video.pov%2Fresources%2Fskins%2FDefault%2Fmedia%2Ftrakt.png\",return)"
    ],
    [
        "10000.1",
        "recommendedshows",
        "widgetTarget",
        "videos"
    ],
    [
        "10000.1",
        "recommendedshows",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "10000.1",
        "recommendedshows",
        "thumb",
        "image://special%3a%2f%2fhome%2faddons%2fplugin.video.pov%2fresources%2fskins%2fDefault%2fmedia%2ftrakt.png/"
    ],
    [
        "10000.1",
        "nextepisodes",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.pov/?name=32483&iconImage=next_episodes.png&mode=build_next_episode\",return)"
    ],
    [
        "10000.1",
        "nextepisodes",
        "widgetTarget",
        "videos"
    ],
    [
        "10000.1",
        "nextepisodes",
        "widgetTags",
        "enable"
    ],
    [
        "10000.1",
        "nextepisodes",
        "widgetTags.name",
        "Enabled"
    ],
    [
        "10000.1",
        "nextepisodes",
        "widgetTagsName",
        "Enabled"
    ],
    [
        "10000.1",
        "nextepisodes",
        "widgetLimit",
        "$NUMBER[200]"
    ],
    [
        "10000.1",
        "nextepisodes",
        "widgetLimit.name",
        "200"
    ],
    [
        "10000.1",
        "nextepisodes",
        "widgetLimitName",
        "200"
    ],
    [
        "10000.1",
        "nextepisodes",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "10000.1",
        "nextepisodes",
        "thumb",
        "image://special%3a%2f%2fhome%2faddons%2fplugin.video.pov%2fresources%2fskins%2fDefault%2fmedia%2fnext_episodes.png/"
    ],
    [
        "mainmenu",
        "137",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "137",
        "icon",
        "shortcuts/search.png"
    ],
    [
        "mainmenu",
        "10000",
        "icon",
        "shortcuts/home.png"
    ],
    [
        "mainmenu",
        "livetv",
        "translatedPath",
        "ActivateWindow(1116,return)"
    ],
    [
        "mainmenu",
        "livetv",
        "icon",
        "shortcuts/antenna.png"
    ],
    [
        "mainmenu",
        "movies",
        "icon",
        "shortcuts/clapperboard.png"
    ],
    [
        "mainmenu",
        "31566",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "31566",
        "icon",
        "shortcuts/tv.png"
    ],
    [
        "mainmenu",
        "favorites",
        "icon",
        "shortcuts/mylist.png"
    ]
]